# Generated by Django 2.2.5 on 2020-01-08 08:22

import courses.models
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=courses.models.get_image_dir)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('enrollees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
